# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jm81-dm-filters}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Morgan"]
  s.date = %q{2010-07-22}
  s.description = %q{This module enables a property in a DataMapper::Resource class to be filtered 
on save into another property, using per-row and/or per-property filters
}
  s.email = %q{jmorgan@morgancreative.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "jm81-dm-filters.gemspec",
     "lib/dm-filters.rb",
     "lib/filters/bible_ml.rb",
     "lib/filters/linebreaker.rb",
     "spec/dm-filters_spec.rb",
     "spec/filters/bible_ml_spec.rb",
     "spec/filters/fixtures/gen11/input.xml",
     "spec/filters/fixtures/gen11/output.xml",
     "spec/filters/linebreaker_spec.rb",
     "spec/filters_resource_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jm81/dm-filters}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Apply text filters to DataMapper properties}
  s.test_files = [
    "spec/filters_resource_spec.rb",
     "spec/spec_helper.rb",
     "spec/filters/bible_ml_spec.rb",
     "spec/filters/linebreaker_spec.rb",
     "spec/dm-filters_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, [">= 0.10.0"])
    else
      s.add_dependency(%q<dm-core>, [">= 0.10.0"])
    end
  else
    s.add_dependency(%q<dm-core>, [">= 0.10.0"])
  end
end

